image:
  repository: khyatipareek/spring-boot-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
